fix(devtools): fix no cancel button while build failed
bramblex/niva pull request #31
Opened 2023-05-19 11:33 UTC by Ir1s666

2023-05-20 03:22 UTC, Ir1s666 commented
虽然但是，这个按钮不放中间真的很丑

2023-05-22 03:39 UTC, bramblex commented
感觉还是不建议修改 prograss 的逻辑，建议如果 prograss 失败了以后，直接关闭 prograss 弹窗，然后弹出一个 alert 弹窗提示错误以及错误信息。这样就不需要懂 prograss 本身的逻辑，就也不会有丑不丑的问题了。

2023-05-22 05:03 UTC, Ir1s666 commented
> 感觉还是不建议修改 prograss 的逻辑，建议如果 prograss 失败了以后，直接关闭 prograss 弹窗，然后弹出一个 alert 弹窗提示错误以及错误信息。这样就不需要懂 prograss 本身的逻辑，就也不会有丑不丑的问题了。

也行，我这个wip吧，我重新改一下这里

2023-05-25 11:56 UTC, Ir1s666 commented
@bramblex done

2023-05-25 15:13 UTC, bramblex requested changes

2023-05-25 15:13 UTC, bramblex commented on packages/devtools/src/modals/index.tsx
> +  const modal = useModal()
这里是 ProgressModal 他只负责一个进度条，并不负责构建，所以把构建错误的逻辑写在这里是没有道理的。

成功和失败的回调统一在这里处理吧：
https://github.com/bramblex/niva/blob/31c3451213bbdfe7fc0b65ff9e638a8aff2327ae/packages/devtools/src/models/project.model.ts#L167

2023-05-25 15:49 UTC, Ir1s666 commented on packages/devtools/src/i18n/zh_CN.ts
> +  BUILD_FAILED: "构建成功",
yes

2023-05-25 15:50 UTC, Ir1s666 commented on packages/devtools/src/i18n/zh_CN.ts
> +  BUILD_FAILED: "构建成功",
不对，这里我早就改了啊，commit不对吧

2023-05-26 06:03 UTC, bramblex requested changes

2023-05-26 06:03 UTC, bramblex commented on packages/devtools/src/build-scripts/base.ts
> +  close: () => void,
这个 close 已经没必要了

2023-05-26 06:03 UTC, bramblex commented on packages/devtools/src/build-scripts/build-macos.ts
> +  progressModel.addTask(locale.t("CREATING_APP_STRUCTURE"), async () => {
这个 progress 的名字别改了呗

2023-05-26 06:03 UTC, bramblex commented on packages/devtools/src/build-scripts/build-windows.ts
>    close();
这部分也可以提出来，progress.run() 和 progress 的 close 都提出去运行

2023-05-26 06:22 UTC, Ir1s666 commented
我被这个mr干晕了...

2023-05-26 07:12 UTC, bramblex requested changes

2023-05-26 07:12 UTC, bramblex commented on packages/devtools/src/build-scripts/build-windows.ts
> -  const file = _target || (await dialog.saveFile(["exe"]));
这一段的逻辑丢了

2023-05-26 07:12 UTC, bramblex commented on packages/devtools/src/models/project.model.ts
> +      const file = target || (await Niva.api.dialog.saveFile(["app"]));
这里只考虑了 mac 没考虑到 windows

2023-05-26 07:24 UTC, bramblex approved these changes

2023-05-26 07:24 UTC, merged