add d.ts file use simplified Chinese
bramblex/niva pull request #59
Opened 2023-05-28 08:53 UTC by lb091188

For more information [see](https://github.com/bramblex/niva/issues/57)

2023-05-29 08:18 UTC, Nctdt requested changes

2023-05-29 08:18 UTC, Nctdt commented on packages/types/Niva_zh.d.ts
> + */
代码格式化一下基本就ok了

2023-05-29 12:47 UTC, lb091188 commented on packages/types/Niva_zh.d.ts
> + */
已经按照根目录的 配置文件对代码进了格式化，请问下怎么添加我新提交的内容到这个PR中来呢，已经推送到了 github,下面貌似能看到我的提交了。麻烦明天看看我的修改是否可以哈，辛苦了

2023-05-30 06:12 UTC, Nctdt approved these changes
没问题 可以合并了

2023-05-30 06:12 UTC, merged